### ISSUE TITLE
animation displaced

### ISSUE THREAD

**Issue by mike44** [der-On/XPlane2Blender#177]
My 3.2 file works fine but in 3.3 all animations are displaced. Attached an example.

[bug_cockpit.blend.zip](https://github.com/der-On/XPlane2Blender/files/219142/bug_cockpit.blend.zip)

**Comment by arb65912** [comment]
Hi Mike44,
I do not see an attachment.

**Comment by mike44** [comment]
sent an mail on x-plane.org forum: 

3.3 displaced 

thanks

**Comment by der-On** [comment]
Attached it to inital post. Just drag and drop files in the text window to attach them.

**Comment by mike44** [comment]
Did so...Anyway you see the lever is drawn to much ahead when exported with 3.3. Same with most other animations. Works fine in 3.2.Thanks

**Comment by mike44** [comment]
Thanks for fixing the displacement. Now in 3.2 it's a manipulator like it should but not in 3.3. Well it doesn't behave like 
a manipulator.Thanks for looking again at my blend file.Regards

**Comment by der-On** [comment]
@mike44 The output of the obj-code shows me the manipulator code just fine. Could you please attach the obj gerenated form 3.2?

**Comment by der-On** [comment]
@mike44 Please do not reply to these emails if you want to attach a file. Those attachments are not delivered to me. To attach a file use the WEB UI of github and simply drag n drop it into the textarea.

**Comment by mike44** [comment]
[Untitled Folder.zip](https://github.com/der-On/XPlane2Blender/files/236228/Untitled.Folder.zip)
attached

**Comment by der-On** [comment]
@mike44 Thx

**Comment by der-On** [comment]
Fixed in [3.3.9](https://github.com/der-On/XPlane2Blender/releases/tag/v3.3.9) now.

**Comment by mike44** [comment]
Thanks for fixing. Now I still see a difference between 3.2 and 3.3. In the attached blend I've deleted all but what I guess is the cause. Anyway why is the output different?
[Untitled Folder 2.zip](https://github.com/der-On/XPlane2Blender/files/238208/Untitled.Folder.2.zip)

**Comment by der-On** [comment]
@mike44 Fixed now.
